{% set name = "kulprit" %}
{% set version = "0.6.0" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/kulprit-{{ version }}.tar.gz
  sha256: 57e2600c97875cee6ec9a27e9066295744e910cdb795fe7aa0629daf2dbd9f88

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.4,<4
    - pip
  run:
    - python >={{ python_min }}
    - arviz-plots >=1.0.0,<2.0.0
    - bambi >=0.18.0,<1.0.0
    - scikit-learn >=1.0.2

test:
  imports:
    - kulprit
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/bambinos/kulprit
  license: MIT
  license_file: LICENSE
  summary: Kullback-Leibler projections for Bayesian model selection
  description: |
    Kulprit is a Python library for variable selection in Bayesian models.
    It is designed to work with Bambi models and to provide tools to
    identify relevant predictors by projecting a reference model onto
    simpler submodels, enabling principled model selection and comparison.
  dev_url: https://github.com/bambinos/kulprit
  doc_url: https://kulprit.readthedocs.io

extra:
  recipe-maintainers:
    - aloctavodia
    - tomicapretto
    - juanitorduz
